### ISSUE TITLE
Ability to @all

### ISSUE THREAD

**Issue by JosephMart** [JosephMart/loki-gm#13]
As a user, I would like to get everyone's attention to something of importance with `@everyone`

Not supported in GroupMe naively

Acceptance Criteria
-----------------
Channel with members P0, P1, P2 & P3
```
P1: @all Check this cool thing out!
Bot: @P0 @P2 @P3 
```
The bot's add should be true, notification causing @'s, not simply the text.

**Comment by JosephMart** [comment]
Regex should probably be something like `/(.*)@all(.*)/i`

**Comment by JosephMart** [comment]
Should original message be preserved?
```
P1: Hey @all check this cool thing out!
Bot: Hey (@P0 @P2 @P3) check this cool thing out!
```

**Comment by JosephMart** [comment]
Mentions are undocumented by GroupMe but figured out by devs 
https://groupy.readthedocs.io/en/latest/pages/quickstart.html#mentions

**Comment by JosephMart** [comment]
guess `sendMessage` needs to support attachments for something like this

https://github.com/JosephMart/loki-gm/blob/3cd041baf053fc665e139b3a0c72ab19b096e57f/src/services/GroupMeService.ts#L24-L27

```
    const json = {
      text,
      bot_id: this.envConfigService.BotID, // eslint-disable-line @typescript-eslint/camelcase
      attachments // type: [{ loci: [int,int][], type: "mentions", user_ids: int[] }]
    };
```

**Comment by tristan957** [comment]
Tonight we can work on it. Is there a good way to get all the users from a groupme?

**Comment by tristan957** [comment]
Uhh I do not think preserving message is necessary. Are there permalinks for messages? Or we just say `@author tagged everyone in a recent message`

**Comment by JosephMart** [comment]
What you mean perma link to the message? You have to parse the message to see if it has @all.

**Comment by tristan957** [comment]
The bot would respond to the group with 

`@user1 @user2, @user3 notified everyone in <permalink>`
